version: "3.8"

services:
  presigner:
    build: .
    container_name: presigner-service
    restart: unless-stopped

    environment:
      PORT: 4000

      # CONFIGURACIÃ“N S3 PARA MINIO
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: resultados-laboratorio
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

      AWS_EC2_METADATA_DISABLED: "true"

    networks:
      - dokploy-network

    ports:
      - "4000:4000"

    labels:
      - traefik.enable=true
      - traefik.http.routers.presigner-router.rule=Host(`presigner.sparkrise.com.co`)
      - traefik.http.routers.presigner-router.entrypoints=websecure
      - traefik.http.routers.presigner-router.tls.certresolver=letsencrypt
      - traefik.http.services.presigner-service.loadbalancer.server.port=4000

networks:
  dokploy-network:
    external: true