version: "3.8"

services:
  presigner:
    build: .
    restart: unless-stopped

    environment:
      PORT: 4000
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: resultados-laboratorio
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_EC2_METADATA_DISABLED: "true"

    networks:
      - dokploy-network

    ports:
      - "4000:4000"

    labels:
      - traefik.enable=true

      # router principal
      - traefik.http.routers.presigner.rule=Host(`presigner.sparkrise.com.co`)
      - traefik.http.routers.presigner.entrypoints=websecure
      - traefik.http.routers.presigner.tls.certresolver=letsencrypt
      - traefik.http.routers.presigner.priority=9999

      # servicio
      - traefik.http.services.presigner.loadbalancer.server.port=4000

networks:
  dokploy-network:
    external: true