version: "3.8"

services:
  presigner:
    build: .
    container_name: presigner-service
    restart: unless-stopped

    environment:
      PORT: 4000
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: resultados-laboratorio
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_EC2_METADATA_DISABLED: "true"

    networks:
      - dokploy-network

    ports:
      - "4000:4000"

    labels:
      - traefik.enable=true

      # ðŸ”¥ Router PRIORITARIO
      - traefik.http.routers.000-presigner.rule=Host(`presigner.sparkrise.com.co`)
      - traefik.http.routers.000-presigner.entrypoints=websecure
      - traefik.http.routers.000-presigner.tls.certresolver=letsencrypt

      # ðŸ”¥ Servidor a enviar trÃ¡fico
      - traefik.http.services.000-presigner-service.loadbalancer.server.port=4000

      #ðŸ”¥ Red de Traefik
      - traefik.docker.network=dokploy-network

networks:
  dokploy-network:
    external: true